import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { posts } from "@/lib/constants";
import { PageHero } from "@/components/ui/PageHero";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = posts.find((item) => item.slug === slug); return { title: post ? post.title : "Blog Post", description: post?.excerpt ?? "Slash Infotech article", openGraph: { title: `${post?.title ?? "Blog Post"} | Slash Infotech`, description: post?.excerpt ?? "Slash Infotech article", images: ["/images/og-image.png"], url: `https://slash-infotech.vercel.app/blog/${slug}` } }; }
export function generateStaticParams() { return posts.map((post) => ({ slug: post.slug })); }
export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const post = posts.find((item) => item.slug === slug); if (!post) notFound(); return <><PageHero eyebrow={post.date} title={post.title} text={post.excerpt} /><article className="mx-auto max-w-3xl px-4 py-20 text-lg leading-9 text-slate-700"><p>Great digital delivery starts with a clear business goal, a realistic technical plan, and the discipline to keep the user experience simple. At Slash Infotech, we use this lens across software, AI, cloud, security, and design projects.</p><p className="mt-6">The teams that move fastest tend to make tradeoffs visible early. They validate assumptions, ship useful slices, measure the right signals, and keep their architecture understandable enough to evolve.</p><p className="mt-6">That is the practical advantage we bring to clients: premium execution without losing sight of launch, adoption, and long-term maintainability.</p></article></>; }

